/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test.scroll;

import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;
import plurker.ui.CallBack;
import plurker.ui.util.ScrollBarAdjustmentListener;

/**
 *
 * @author SkyforceShen
 */
public class ScrollTestFrame extends javax.swing.JFrame implements ScrollBarAdjustmentListener.TriggerInterface {

    /**
     * Creates new form ScrollTestFrame
     */
    public ScrollTestFrame() {
        initComponents();
        for (int x = 0; x < 20; x++) {
            this.jPanel1.add(new JLabel(Integer.toString(x)));
        }
        final JScrollBar verticalScrollBar = this.jScrollPane1.getVerticalScrollBar();
        verticalScrollBar.addAdjustmentListener(adjustmentListener);

        ScrollBarAdjustmentListener listener = new ScrollBarAdjustmentListener(jPanel1, true, this);
        verticalScrollBar.addAdjustmentListener(listener);
//        verticalScrollBar.setValueIsAdjusting(false);

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
//                    Thread.currentThread().sleep(1000);
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ScrollTestFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
//                verticalScrollBar.setValue(10);


                JViewport viewport = jScrollPane1.getViewport();
                viewport.setViewPosition(new Point(0, jPanel1.getPreferredSize().height));
//                System.out.println(verticalScrollBar.getValueIsAdjusting());
//                verticalScrollBar.setValueIsAdjusting(rootPaneCheckingEnabled);
            }
        });
    }
    AdjustmentListener adjustmentListener = new AdjustmentListener() {
        @Override
        public void adjustmentValueChanged(AdjustmentEvent e) {
//            System.out.println(e);
//            System.out.println(e.getSource());
//            System.out.println(e.getAdjustable());
//            System.out.println(e.getAdjustmentType());
//            System.out.println(e.getValueIsAdjusting() + " " + e.getValue());
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrollTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void trigger(boolean topProcess, JPanel panel, CallBack callBack) {
        System.out.println("trigger");
        callBack.callback();
    }
}
