/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plurker.ui;

import com.google.jplurk_oauth.data.Comment;
import com.google.jplurk_oauth.data.Plurk;
import plurker.source.PlurkPool;

/**
 *
 * @author SkyforceShen
 */
public class NotifyPanel extends javax.swing.JPanel {

    private Plurk plurk;
    private Comment comment;
    private PlurkPool plurkPool;

    /**
     * Creates new form NotifyPanel
     */
    private NotifyPanel(Plurk plurk, Comment comment, PlurkPool plurkPool) {
        initComponents();
        this.plurk = plurk;
        this.comment = comment;
        this.plurkPool = plurkPool;
    }

    public NotifyPanel(Plurk plurk, PlurkPool plurkPool) {
        this(plurk, null, plurkPool);
    }

    public NotifyPanel(Comment comment, PlurkPool plurkPool) {
        this(null, comment, plurkPool);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Avatar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jLabel_Avatar.setName(""); // NOI18N
        add(jLabel_Avatar, java.awt.BorderLayout.WEST);

        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel_Avatar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
