/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plurker.ui;

import plurker.ui.util.GUIUtil;
import java.awt.Window;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import org.sexydock.tabs.DefaultTabbedPaneWindowFactory;
import org.sexydock.tabs.ITab;
import org.sexydock.tabs.ITabbedPaneWindow;
import org.sexydock.tabs.TabbedPane;
import org.sexydock.tabs.demos.NonUniformTabWidthDemo;
import org.sexydock.tabs.demos.SexyTabsDemos;
import org.sexydock.tabs.launchers.TabTest;

/**
 *
 * @author SkyforceShen
 */
public class MessengerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MessengerFrame
     */
    public MessengerFrame() {
        initComponents();
        try {
            this.setIconImages(GUIUtil.getIconImages("image/bubble.ico"));
        } catch (IOException ex) {
            Logger.getLogger(MessengerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        tabbedPane = new TabbedPane();
//        tabbedPane.getNewTabButton().setVisible(false);
//        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);
    }
    private TabbedPane tabbedPane;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 700));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("動作(A)");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("工具(T)");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("說明(H)");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        SwingUtilities.invokeLater(new Runnable() {
//
//            @Override
//            public void run() {
//                DefaultTabbedPaneWindowFactory windowFactory = new DefaultTabbedPaneWindowFactory() {
//
//                    @Override
//                    public ITabbedPaneWindow createWindow() {
//                        showNewTabButton = false;
//                        ITabbedPaneWindow window = super.createWindow();
//                        window.getTabbedPane().setUseUniformWidth(false);
//                        return window;
//                    }
//                };
//                ITabbedPaneWindow tabbedPaneWindow = windowFactory.createWindow();
//
//                TabbedPane tabbedPane = tabbedPaneWindow.getTabbedPane();
//                ITab tab1 = tabbedPane.getTabFactory().createTab("Tab 1");
//                tabbedPane.addTab(tab1);
////                tabbedPaneWindow.getTabbedPane().setSelectedTab(tab1);
//
//                Window window = tabbedPaneWindow.getWindow();
//                window.setSize(800, 600);
//                window.setLocationRelativeTo(null);
//                window.setVisible(true);
//            }
//        });


        GUIUtil.initGUI();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MessengerFrame messengerFrame = new MessengerFrame();
                messengerFrame.jTabbedPane1.add(new MessengerPanel());

                messengerFrame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
