/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plurker.ui;

import com.ctreber.aclib.image.ico.ICOFile;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
//import shu.image.ImageUtils;

/**
 *
 * @author SkyforceShen
 */
public class MessengerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MessengerPanel
     */
    public MessengerPanel() {
        initComponents();
//        try {
//            //     this.jButton_Emoticon.setIcon(null);
//            Icon emoticonicon = new ImageIcon((Image) getIconImages("image/emoticon.ico").get(2));
//            this.jButton_Emoticon.setIcon(emoticonicon);
//            this.jButton_Font.setIcon(new ImageIcon("image/font.png"));
////            ImageUtils.loadImage(TOOL_TIP_TEXT_KEY)
//            Icon themenicon = new ImageIcon((Image) getIconImages("image/theme.ico").get(2));
//            this.jButton_Theme.setIcon(themenicon);
//            
//        } catch (IOException ex) {
//            Logger.getLogger(MessengerPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel_UserAvatar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_UserStatus = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton_Transmission = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane_Input = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jButton_Emoticon = new javax.swing.JButton();
        jButton_Font = new javax.swing.JButton();
        jButton_Theme = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel_UserAvatar.setText("Avatar");
        jPanel3.add(jLabel_UserAvatar, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel_UserName.setText("UserName");
        jPanel1.add(jLabel_UserName);

        jLabel_UserStatus.setText("UserStatus");
        jPanel1.add(jLabel_UserStatus);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton_Transmission.setText("傳送");
        jButton_Transmission.setEnabled(false);
        jButton_Transmission.setPreferredSize(new java.awt.Dimension(80, 23));
        jPanel5.add(jButton_Transmission, java.awt.BorderLayout.EAST);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(108, 70));
        jScrollPane2.setViewportView(jEditorPane_Input);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 27));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButton_Emoticon.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\Netbean\\plurker\\workdir\\image\\emoticon.png")); // NOI18N
        jButton_Emoticon.setText("表情符號");
        jButton_Emoticon.setPreferredSize(new java.awt.Dimension(110, 27));
        jPanel2.add(jButton_Emoticon);

        jButton_Font.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\Netbean\\plurker\\workdir\\image\\font.png")); // NOI18N
        jButton_Font.setText("字型");
        jButton_Font.setPreferredSize(new java.awt.Dimension(85, 27));
        jPanel2.add(jButton_Font);

        jButton_Theme.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\Netbean\\plurker\\workdir\\image\\theme.png")); // NOI18N
        jButton_Theme.setText("背景");
        jButton_Theme.setPreferredSize(new java.awt.Dimension(85, 27));
        jPanel2.add(jButton_Theme);

        jPanel5.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Emoticon;
    private javax.swing.JButton jButton_Font;
    private javax.swing.JButton jButton_Theme;
    private javax.swing.JButton jButton_Transmission;
    private javax.swing.JEditorPane jEditorPane_Input;
    private javax.swing.JLabel jLabel_UserAvatar;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_UserStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}
