/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plurker.ui.tooltip;

import com.google.jplurk_oauth.data.Plurk;
import com.google.jplurk_oauth.data.Plurk.PlurkType;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.json.JSONException;
import plurker.source.PlurkPool;
import plurker.source.PlurkSourcer;
import plurker.ui.ContentPanel;
import plurker.ui.GUIUtil;

/**
 *
 * @author SkyforceShen
 */
public class PlurkToolTipPanel extends ToolTipPanel {

    /**
     * Creates new form PlurkerToolTipPanel
     */
    public PlurkToolTipPanel(PlurkPool plurkPool, Plurk plurk, ContentPanel contentPanel) {
        super(plurkPool, contentPanel);
        initComponents();
//        this.sourcer = sourcer;
        this.plurk = plurk;
        init();
    }
//    private PlurkSourcer sourcer;
    private Plurk plurk;

    private void init() {
        try {
            long userID = sourcer.getUserID();
            long ownerId = plurk.getOwnerId();


            if (userID != ownerId) {
                jLabel_Delete.setVisible(false);
                jLabel_Edit.setVisible(false);
            } else {
                jLabel_Mute.setVisible(false);
            }
            PlurkType plurkType = plurk.getPlurkType();
            if (userID == ownerId || plurkType == PlurkType.Private_Logged || plurkType == PlurkType.Private) {
                jLabel_Promote.setVisible(false);
                jLabel_Replurk.setVisible(false);
            }
        } catch (JSONException ex) {
            Logger.getLogger(PlurkToolTipPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Delete = new javax.swing.JLabel();
        jLabel_Edit = new javax.swing.JLabel();
        jLabel_Mute = new javax.swing.JLabel();
        jLabel_Promote = new javax.swing.JLabel();
        jLabel_Replurk = new javax.swing.JLabel();
        jLabel_Like = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Delete.setText("刪除");
        add(jLabel_Delete);

        jLabel_Edit.setText("編輯");
        add(jLabel_Edit);

        jLabel_Mute.setText("消音");
        jLabel_Mute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseExited(evt);
            }
        });
        add(jLabel_Mute);

        jLabel_Promote.setText("推文");
        jLabel_Promote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseExited(evt);
            }
        });
        add(jLabel_Promote);

        jLabel_Replurk.setText("轉噗");
        jLabel_Replurk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseExited(evt);
            }
        });
        add(jLabel_Replurk);

        jLabel_Like.setText("讚");
        jLabel_Like.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MuteMouseExited(evt);
            }
        });
        add(jLabel_Like);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MuteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MuteMouseEntered
        JLabel source = (JLabel) evt.getSource();
        source.setFont(GUIUtil.boldFont);
    }//GEN-LAST:event_jLabel_MuteMouseEntered

    private void jLabel_MuteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MuteMouseExited
        JLabel source = (JLabel) evt.getSource();
        source.setFont(GUIUtil.font);
    }//GEN-LAST:event_jLabel_MuteMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Delete;
    private javax.swing.JLabel jLabel_Edit;
    private javax.swing.JLabel jLabel_Like;
    private javax.swing.JLabel jLabel_Mute;
    private javax.swing.JLabel jLabel_Promote;
    private javax.swing.JLabel jLabel_Replurk;
    // End of variables declaration//GEN-END:variables
}
