/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;

/**
 *
 * @author SkyforceShen
 */
public class ScrollTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form ScrollTestFrame
     */
    public ScrollTestFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setVerticalScrollBar(jScrollBar1);
        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentShown(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int index = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
        JViewport viewport = jScrollPane1.getViewport();
//        System.out.println("scrollpanel: " + jScrollPane1.getSize());

        for (int x = 0; x < 10; x++) {
            JPanel panel = new JPanel();
            panel.add(new JLabel(Integer.toString(index++)));
            panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            panel.setPreferredSize(new Dimension(200, 50));
//
            jPanel1.add(panel);

//            jPanel1.add(new JLabel(Integer.toString(index++)));

//            System.out.println(panel.getLocation());
//            System.out.println(panel.getLocationOnScreen());
//            SwingUtilities.
            jPanel1.updateUI();
            jScrollPane1.updateUI();
//jScrollPane1.scrollRectToVisible(null);
        }

//        System.out.println(jPanel1.getSize() + " " + jPanel1.getPreferredSize());
//        jPanel1.setPreferredSize(new Dimension(jPanel1.getSize().width, jPanel1.getPreferredSize().height * 2));
//        jScrollPane1.updateUI();
        JScrollBar verticalScrollBar1 = jScrollPane1.getVerticalScrollBar();
        verticalScrollBar1.updateUI();
        //        verticalScrollBar1.setValue(verticalScrollBar1.getMaximum());
        //        jScrollPane1.updateUI();
        //        jScrollPane1.repaint();
        //        System.out.println("in"+verticalScrollBar1.getMaximum());
        System.out.println(jPanel1.getPreferredSize() + " " + jPanel1.getSize());
        JViewport viewport1 = jScrollPane1.getViewport();
        viewport1.setViewPosition(new Point(0, jPanel1.getPreferredSize().height));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentShown
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
//        System.out.println("jScrollPane1ComponentShown" + verticalScrollBar.getMaximum());
    }//GEN-LAST:event_jScrollPane1ComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        final JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
//        System.out.println("formWindowOpened" + verticalScrollBar.getMaximum());

//                                JViewport viewport = (JViewport) jPanel_Comments.getParent();
//                        JScrollPane scrollPane = (JScrollPane) viewport.getParent();
//                        final JScrollBar verticalScrollBar = scrollPane.getVerticalScrollBar();
        verticalScrollBar.addAdjustmentListener(new AdjustmentListener() {
            @Override
            public void adjustmentValueChanged(AdjustmentEvent e) {
//                System.out.println(verticalScrollBar.getValue() + " " + verticalScrollBar.getMaximum() + " " + verticalScrollBar.getVisibleAmount());
            }
        });

//        System.out.println(verticalScrollBar.getValue() + " " + verticalScrollBar.getMaximum() + " " + verticalScrollBar.getVisibleAmount());

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
//        System.out.println("formWindowActivated" + verticalScrollBar.getMaximum());

    }//GEN-LAST:event_formWindowActivated

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        System.out.println(this.jScrollBar1.getMaximum());
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrollTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrollTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
